import { asc } from "drizzle-orm";
import { SiteFooter } from "@/components/storefront/site-footer";
import { SiteHeader } from "@/components/storefront/site-header";
import { db, pgClient } from "@/lib/db";
import { categories } from "@/lib/db/schema";

const CATEGORIES_TIMEOUT_MS = 8000;

interface CategoryLink {
  name: string;
  slug: string;
}

// The categories fetch below now gates every storefront page through this
// shared layout, including ones that attempt static generation (see the
// cart-badge fix below). The Supabase pooler has a documented habit of
// occasionally hanging well past a normal response time — previously that
// only ever cost one slow/failed request, but a hang during `next build`'s
// static generation can eat Next's 60s per-page budget and fail the entire
// deployment.
//
// A plain `Promise.race` against a timeout (the original version of this
// function, still the pattern to reach for elsewhere) only stops THIS
// function from waiting — it doesn't cancel the underlying Postgres query,
// which keeps running server-side, still holding one of only ~10 pooled
// connections, until it actually resolves. During a real pooler-hang
// episode, a burst of concurrent requests each abandoning-but-not-cancelling
// their query could exhaust the whole pool — turning a contained per-page
// failure into a site-wide cascade, the opposite of the resilience this
// timeout exists for.
//
// Fixed by issuing the query through the raw postgres.js client (`pgClient`,
// lib/db/index.ts) instead of via getCategories()/Drizzle's `db.select()`
// directly, so we hold a real, cancellable Query handle — Drizzle's
// QueryPromise awaits `client.unsafe(...)` internally and never exposes one
// (see lib/db/index.ts's `pgClient` export comment). On timeout we call
// `.cancel()`, which sends a genuine Postgres CancelRequest over a fresh
// connection: verified live that this actually terminates the query
// server-side and frees the pooled connection, including through Supabase's
// transaction-mode pooler, where a plain session-level `statement_timeout`
// does NOT take effect (see lib/db/index.ts's STATEMENT_TIMEOUT_MS comment —
// that was the first approach tried here, confirmed via a live test against
// the dev DB to be silently ignored by the pooler before this was written).
//
// The query text itself is still generated by Drizzle (`db.select(...)
// .toSQL()`), so it stays in sync with the `categories` table/column
// definitions — only its *execution* bypasses Drizzle's own runner. Falls
// back to an empty list on either a rejection or a timeout:
// SiteHeader/SiteFooter already render a graceful empty state, and the next
// revalidatePath("/") from any admin category edit fixes a stale/empty
// result immediately.
async function getCategoriesSafe(): Promise<CategoryLink[]> {
  const { sql, params } = db
    .select({ name: categories.name, slug: categories.slug })
    .from(categories)
    .orderBy(asc(categories.sortOrder))
    .toSQL();

  const query = pgClient.unsafe<CategoryLink[]>(sql, params as never[]);
  const timer = setTimeout(() => query.cancel(), CATEGORIES_TIMEOUT_MS);

  try {
    return await query;
  } catch (err) {
    console.error(
      "[storefront layout] getCategories failed — rendering empty nav:",
      err,
    );
    return [];
  } finally {
    clearTimeout(timer);
  }
}

export default async function StorefrontLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Deliberately no getCart() here. It reads the guest-cart cookie, and any
  // dynamic API read in a shared layout forces every nested page onto
  // per-request dynamic rendering — the whole storefront lost static
  // generation/ISR over one header badge (see CLAUDE.md's "Badge trade-off").
  // SiteHeader now hydrates the cart count client-side instead.
  const categoryLinks = await getCategoriesSafe();

  return (
    <>
      <SiteHeader categories={categoryLinks} />
      <main className="flex-1">{children}</main>
      <SiteFooter categories={categoryLinks} />
    </>
  );
}
