import { asc } from "drizzle-orm";
import { SiteFooter } from "@/components/storefront/site-footer";
import { SiteHeader } from "@/components/storefront/site-header";
import { db, pgClient } from "@/lib/db";
import { safeDbRead, SAFE_DB_READ_TIMEOUT_MS } from "@/lib/db/safe-query";
import { categories } from "@/lib/db/schema";

interface CategoryLink {
  name: string;
  slug: string;
}

// This categories fetch gates EVERY storefront page — the shared layout runs
// on all of them, and Next trial-renders every page during `next build`. A
// Supabase pooler hang here (the pooler intermittently stops responding, see
// lib/db/index.ts) therefore threatens the whole deployment: one hung render
// blows Next's 60s per-page budget and fails the build. This has repeatedly
// taken down real production deploys.
//
// safeDbRead guarantees this returns within the timeout no matter what —
// crucially, even when the pooler is distressed enough that a query cancel
// can't get a connection through either (the failure mode the previous
// await-then-cancel version could still hang the entire build on; see
// lib/db/safe-query.ts for the full story).
//
// This is the one storefront hot path where freeing the abandoned pooled
// connection under sustained *live* traffic matters (not just surviving the
// build), so it issues the query through the raw postgres.js client
// (`pgClient`) to hold a real cancellable handle and fires `.cancel()` from
// onTimeout — a genuine Postgres CancelRequest that works through the
// transaction-mode pooler where a session-level statement_timeout does not
// (see lib/db/index.ts). That cancel is now purely best-effort cleanup: the
// fallback below is returned whether or not it gets through.
//
// The query text is still generated by Drizzle (`.toSQL()`) so it stays in
// sync with the `categories` schema; only its execution bypasses Drizzle's
// runner to expose the cancellable handle. Falls back to an empty list —
// SiteHeader/SiteFooter render a graceful empty state, and the next
// revalidatePath("/") from any admin category edit repairs a stale/empty
// result immediately.
async function getCategoriesSafe(): Promise<CategoryLink[]> {
  const { sql, params } = db
    .select({ name: categories.name, slug: categories.slug })
    .from(categories)
    .orderBy(asc(categories.sortOrder))
    .toSQL();

  const query = pgClient.unsafe<CategoryLink[]>(sql, params as never[]);

  return safeDbRead(query as unknown as Promise<CategoryLink[]>, {
    timeoutMs: SAFE_DB_READ_TIMEOUT_MS,
    fallback: [],
    label: "storefront categories",
    onTimeout: () => query.cancel(),
  });
}

export default async function StorefrontLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Deliberately no getCart() here. It reads the guest-cart cookie, and any
  // dynamic API read in a shared layout forces every nested page onto
  // per-request dynamic rendering — the whole storefront lost static
  // generation/ISR over one header badge (see CLAUDE.md's "Badge trade-off").
  // SiteHeader now hydrates the cart count client-side instead.
  const categoryLinks = await getCategoriesSafe();

  return (
    <>
      <SiteHeader categories={categoryLinks} />
      <main className="flex-1">{children}</main>
      <SiteFooter categories={categoryLinks} />
    </>
  );
}
