import type { MetadataRoute } from "next";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://shopaarna.in";

/**
 * Robots.txt — generated by Next.js at /robots.txt.
 *
 * We block /account (user-specific, also no SEO value), /api (server
 * endpoints), and /auth-related flows. Everything else is open to crawlers.
 *
 * The admin path is deliberately NOT listed here — robots.txt is a public
 * file, and naming an intentionally-obscure admin route here would be
 * exactly how a scanner finds it. It's still fully access-gated (real auth +
 * an admins-table check, see app/studio/layout.tsx) and carries its own
 * `robots: noindex` metadata, so omitting it here is belt-and-suspenders,
 * not the only protection.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/api",
          "/api/",
          "/account",
          "/account/",
          "/login",
          "/login/",
          "/signup",
          "/auth/",
          "/cart",
          "/checkout",
          "/payment-processing",
          "/payment-failed",
          "/order-confirmation/",
        ],
      },
    ],
    sitemap: `${APP_URL}/sitemap.xml`,
    host: APP_URL,
  };
}
