import type { MetadataRoute } from "next";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://shopaarna.in";

/**
 * Robots.txt — generated by Next.js at /robots.txt.
 *
 * We block /admin (private), /account (user-specific, also no SEO value),
 * /api (server endpoints), and /auth-related flows. Everything else is open
 * to crawlers.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/admin",
          "/admin/",
          "/api",
          "/api/",
          "/account",
          "/account/",
          "/login",
          "/signup",
          "/forgot-password",
          "/reset-password",
          "/auth/callback",
          "/cart",
          "/checkout",
        ],
      },
    ],
    sitemap: `${APP_URL}/sitemap.xml`,
    host: APP_URL,
  };
}
