import type { MetadataRoute } from "next";
import { db, schema } from "@/lib/db";
import { eq } from "drizzle-orm";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://aarna.in";

/**
 * Dynamic sitemap.xml — generated by Next.js at /sitemap.xml.
 *
 * Includes:
 * - Static high-value pages (home, shop, collections, legal)
 * - Every active product (uses updatedAt as lastModified)
 * - Every category (slug-based shop pages)
 * - Every active collection (slug-based collection pages)
 *
 * Excludes admin, account, cart, checkout, auth (handled by robots.txt).
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const [products, categories, collections] = await Promise.all([
    db
      .select({
        slug: schema.products.slug,
        updatedAt: schema.products.updatedAt,
      })
      .from(schema.products)
      .where(eq(schema.products.status, "active")),
    db
      .select({
        slug: schema.categories.slug,
      })
      .from(schema.categories),
    db
      .select({
        slug: schema.collections.slug,
      })
      .from(schema.collections)
      .where(eq(schema.collections.isActive, true)),
  ]);

  const now = new Date();

  const staticPages: MetadataRoute.Sitemap = [
    { url: `${APP_URL}/`, lastModified: now, changeFrequency: "daily", priority: 1.0 },
    { url: `${APP_URL}/shop`, lastModified: now, changeFrequency: "daily", priority: 0.9 },
    { url: `${APP_URL}/collections`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${APP_URL}/privacy`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${APP_URL}/terms`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${APP_URL}/returns`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${APP_URL}/shipping`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
  ];

  const productPages: MetadataRoute.Sitemap = products.map((p) => ({
    url: `${APP_URL}/product/${p.slug}`,
    lastModified: p.updatedAt,
    changeFrequency: "weekly" as const,
    priority: 0.8,
  }));

  const categoryPages: MetadataRoute.Sitemap = categories.map((c) => ({
    url: `${APP_URL}/shop/${c.slug}`,
    lastModified: now,
    changeFrequency: "daily" as const,
    priority: 0.7,
  }));

  const collectionPages: MetadataRoute.Sitemap = collections.map((c) => ({
    url: `${APP_URL}/collections/${c.slug}`,
    lastModified: now,
    changeFrequency: "weekly" as const,
    priority: 0.7,
  }));

  return [
    ...staticPages,
    ...categoryPages,
    ...collectionPages,
    ...productPages,
  ];
}
