import type { MetadataRoute } from "next";
import { db, schema } from "@/lib/db";
import { eq } from "drizzle-orm";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://shopaarna.in";

/**
 * Dynamic sitemap.xml — generated by Next.js at /sitemap.xml.
 *
 * Includes:
 * - Static high-value pages (home, shop, legal, faq)
 * - Every active product (uses updatedAt as lastModified)
 * - Every category (slug-based shop pages)
 *
 * Excludes admin, account, cart, checkout, auth (handled by robots.txt).
 * Collections are excluded until the /collections routes actually exist —
 * advertising them here fed 404s straight to crawlers. Restore the
 * collections query + page block when the route ships.
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const [products, categories] = await Promise.all([
    db
      .select({
        slug: schema.products.slug,
        updatedAt: schema.products.updatedAt,
      })
      .from(schema.products)
      .where(eq(schema.products.status, "active")),
    db
      .select({
        slug: schema.categories.slug,
      })
      .from(schema.categories),
  ]);

  const now = new Date();

  const staticPages: MetadataRoute.Sitemap = [
    { url: `${APP_URL}/`, lastModified: now, changeFrequency: "daily", priority: 1.0 },
    { url: `${APP_URL}/shop`, lastModified: now, changeFrequency: "daily", priority: 0.9 },
    { url: `${APP_URL}/faq`, lastModified: now, changeFrequency: "monthly", priority: 0.4 },
    { url: `${APP_URL}/privacy-policy`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${APP_URL}/terms`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${APP_URL}/return-policy`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${APP_URL}/shipping-policy`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${APP_URL}/fabric-care`, lastModified: now, changeFrequency: "yearly", priority: 0.4 },
    { url: `${APP_URL}/contact`, lastModified: now, changeFrequency: "yearly", priority: 0.4 },
  ];

  const productPages: MetadataRoute.Sitemap = products.map((p) => ({
    url: `${APP_URL}/product/${p.slug}`,
    lastModified: p.updatedAt,
    changeFrequency: "weekly" as const,
    priority: 0.8,
  }));

  const categoryPages: MetadataRoute.Sitemap = categories.map((c) => ({
    url: `${APP_URL}/shop/${c.slug}`,
    lastModified: now,
    changeFrequency: "daily" as const,
    priority: 0.7,
  }));

  return [...staticPages, ...categoryPages, ...productPages];
}
