import {
  Document,
  Image,
  Page,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";
import path from "path";

// Aarna monogram mark — 120px downscaled copy (the full-res brand PNG bloats
// every tag page by ~150KB; at 10pt the small copy is visually identical).
// Prints as solid black on thermal.
const LOGO_MARK_PATH = path.join(
  process.cwd(),
  "public",
  "brand",
  "aarna-mark-tag.png",
);

// ── Types ────────────────────────────────────────────────────────────────────

export interface HangTagData {
  productTitle: string;
  size: string | null;
  color: string | null;
  sku: string;
  /** MRP in paise — required on Indian garment labels (Legal Metrology Act) */
  mrp: number | null;
  fabric: string | null;
  careInstructions: string | null;
  /** PNG buffer of the Code 128 barcode encoding the SKU. Generated by bwip-js. */
  barcodePng: Buffer;
}

// "Rs." not "₹" — the built-in Helvetica PDF font has no rupee glyph (it
// renders as "¹").
const INR = (paise: number) =>
  `Rs.${(paise / 100).toLocaleString("en-IN", { minimumFractionDigits: 0 })}`;

// ── Styles ───────────────────────────────────────────────────────────────────

// 50mm × 30mm at 72 DPI
const LABEL_WIDTH_PT = 141.7; // 50mm
const LABEL_HEIGHT_PT = 85; // 30mm

const s = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    color: "#000000",
    backgroundColor: "#FFFFFF",
    padding: 5,
  },
  container: {
    flexDirection: "column",
    height: "100%",
    justifyContent: "space-between",
  },
  brandRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 3,
  },
  brandMark: {
    width: 10,
    height: 10,
    objectFit: "contain",
  },
  brand: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 2,
    textAlign: "center",
  },
  title: {
    fontSize: 6.5,
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
    lineHeight: 1.1,
  },
  sizeMrpRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 1,
  },
  size: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
  },
  mrp: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    textAlign: "right",
  },
  micro: {
    fontSize: 4.5,
    color: "#333333",
    lineHeight: 1.2,
  },
  barcode: {
    width: "100%",
    height: 18,
    objectFit: "contain",
  },
  skuText: {
    fontSize: 5,
    textAlign: "center",
    letterSpacing: 0.5,
  },
});

// ── Component ────────────────────────────────────────────────────────────────

export function HangTagDocument({ tags }: { tags: HangTagData[] }) {
  return (
    <Document title="Aarna Hang Tags" author="Aarna Label">
      {tags.map((tag, i) => (
        <Page
          key={i}
          size={{ width: LABEL_WIDTH_PT, height: LABEL_HEIGHT_PT }}
          style={s.page}
        >
          <View style={s.container}>
            {/* Top: logo mark + brand + product name */}
            <View>
              <View style={s.brandRow}>
                {/* eslint-disable-next-line jsx-a11y/alt-text -- react-pdf Image */}
                <Image src={LOGO_MARK_PATH} style={s.brandMark} />
                <Text style={s.brand}>AARNA</Text>
              </View>
              <Text style={s.title}>{truncate(tag.productTitle, 40)}</Text>
            </View>

            {/* Middle: size + MRP */}
            <View style={s.sizeMrpRow}>
              <Text style={s.size}>{tag.size ? `Size: ${tag.size}` : ""}</Text>
              {tag.mrp !== null ? (
                <Text style={s.mrp}>MRP {INR(tag.mrp)}</Text>
              ) : null}
            </View>

            {/* Micro-print: fabric + care + HSN */}
            <View>
              {tag.fabric ? (
                <Text style={s.micro}>{truncate(tag.fabric, 50)}</Text>
              ) : null}
              {tag.careInstructions ? (
                <Text style={s.micro}>{truncate(tag.careInstructions, 50)}</Text>
              ) : null}
              <Text style={s.micro}>HSN: 6211 · Inclusive of all taxes</Text>
            </View>

            {/* Bottom: Code 128 barcode + SKU text */}
            <View>
              {/* eslint-disable-next-line jsx-a11y/alt-text -- react-pdf Image, not html img */}
              <Image src={tag.barcodePng} style={s.barcode} />
              <Text style={s.skuText}>{tag.sku}</Text>
            </View>
          </View>
        </Page>
      ))}
    </Document>
  );
}

function truncate(s: string, max: number): string {
  return s.length <= max ? s : s.slice(0, max - 1) + "…";
}
