import {
  Document,
  Image,
  Page,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";
import path from "path";

// Aarna monogram mark — 120px downscaled copy (the full-res brand PNG bloats
// every tag page by ~150KB; at 10pt the small copy is visually identical).
// Prints as solid black on thermal.
const LOGO_MARK_PATH = path.join(
  process.cwd(),
  "public",
  "brand",
  "aarna-mark-tag.png",
);

// ── Types ────────────────────────────────────────────────────────────────────

export interface HangTagData {
  productTitle: string;
  size: string | null;
  color: string | null;
  sku: string;
  /** MRP in paise — required on Indian garment labels (Legal Metrology Act) */
  mrp: number | null;
  fabric: string | null;
  careInstructions: string | null;
  /** PNG buffer of the Code 128 barcode encoding the SKU. Generated by bwip-js. */
  barcodePng: Buffer;
}

// "Rs." not "₹" — the built-in Helvetica PDF font has no rupee glyph (it
// renders as "¹").
const INR = (paise: number) =>
  `Rs.${(paise / 100).toLocaleString("en-IN", { minimumFractionDigits: 0 })}`;

// ── Styles ───────────────────────────────────────────────────────────────────

// 50mm × 30mm at 72 DPI
const LABEL_WIDTH_PT = 141.7; // 50mm
const LABEL_HEIGHT_PT = 85; // 30mm

const s = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    color: "#000000",
    backgroundColor: "#FFFFFF",
    padding: 4,
  },
  border: {
    position: "relative",
    height: "100%",
    width: "100%",
    borderWidth: 1.2,
    borderColor: "#000000",
    borderRadius: 5,
    paddingVertical: 4,
    paddingLeft: 5,
    paddingRight: 14,
  },
  main: {
    height: "100%",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  barcode: {
    width: "100%",
    height: 20,
    objectFit: "contain",
  },
  skuText: {
    fontSize: 5,
    textAlign: "center",
    letterSpacing: 0.5,
    marginTop: 1,
  },
  title: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
    lineHeight: 1.1,
    marginTop: 1,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 1,
  },
  infoCol: {
    flexDirection: "column",
  },
  mrp: {
    fontSize: 6.5,
    fontFamily: "Helvetica-Bold",
  },
  size: {
    fontSize: 6.5,
    fontFamily: "Helvetica-Bold",
    marginTop: 2,
  },
  micro: {
    fontSize: 6,
    color: "#1a1a1a",
    lineHeight: 1.35,
    textAlign: "right",
  },
  brandRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 3,
    marginTop: 1,
  },
  brandMark: {
    width: 12,
    height: 12,
    objectFit: "contain",
  },
  brand: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 1.5,
    textAlign: "center",
  },
  hsnWrap: {
    position: "absolute",
    top: 0,
    bottom: 0,
    right: 0,
    width: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  hsn: {
    width: 65,
    fontSize: 6,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 0.3,
    textAlign: "center",
    transform: "rotate(-90deg)",
  },
});

// ── Component ────────────────────────────────────────────────────────────────

export function HangTagDocument({ tags }: { tags: HangTagData[] }) {
  return (
    <Document title="Aarna Hang Tags" author="Aarna Label">
      {tags.map((tag, i) => (
        <Page
          key={i}
          size={{ width: LABEL_WIDTH_PT, height: LABEL_HEIGHT_PT }}
          style={s.page}
        >
          <View style={s.border}>
            <View style={s.main}>
              {/* Top: Code 128 barcode + SKU text */}
              <View>
                {/* eslint-disable-next-line jsx-a11y/alt-text -- react-pdf Image, not html img */}
                <Image src={tag.barcodePng} style={s.barcode} />
                <Text style={s.skuText}>{tag.sku}</Text>
              </View>

              {/* Product name */}
              <Text style={s.title}>{truncate(tag.productTitle, 32)}</Text>

              {/* MRP + size (left) vs. fabric + care (right) — each row is
                  always rendered (blank if the data is missing) so the two
                  columns stay aligned instead of collapsing upward. */}
              <View style={s.infoRow}>
                <View style={s.infoCol}>
                  <Text style={s.mrp}>
                    {tag.mrp !== null ? `M.R.P : ${INR(tag.mrp)}-/` : " "}
                  </Text>
                  <Text style={s.size}>
                    {tag.size ? `Size : ${tag.size}` : " "}
                  </Text>
                </View>
                <View style={s.infoCol}>
                  <Text style={s.micro}>
                    {tag.fabric ? truncate(tag.fabric, 30) : " "}
                  </Text>
                  <Text style={s.micro}>
                    {tag.careInstructions
                      ? truncate(tag.careInstructions, 30)
                      : " "}
                  </Text>
                </View>
              </View>

              {/* Bottom: logo mark + wordmark */}
              <View style={s.brandRow}>
                {/* eslint-disable-next-line jsx-a11y/alt-text -- react-pdf Image */}
                <Image src={LOGO_MARK_PATH} style={s.brandMark} />
                <Text style={s.brand}>AARNA</Text>
              </View>
            </View>

            {/* Right edge: vertical HSN code (Legal Metrology requirement) */}
            <View style={s.hsnWrap}>
              <Text style={s.hsn}>HSN: 6211</Text>
            </View>
          </View>
        </Page>
      ))}
    </Document>
  );
}

function truncate(s: string, max: number): string {
  return s.length <= max ? s : s.slice(0, max - 1) + "…";
}
